In [3]:
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.8899, 0.1468, 0.8998],
        [0.6398, 0.7436, 0.3241],
        [0.4016, 0.7789, 0.4622],
        [0.0081, 0.3447, 0.3749],
        [0.8538, 0.4158, 0.1942]])


In [4]:
torch.cuda.is_available()

True

## PyTorch tensors

In [5]:
import numpy as np

#### Tensor from data

In [6]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [7]:
x_data

tensor([[1, 2],
        [3, 4]])

#### Tensor from np.array

In [10]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [12]:
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### Tensor from another tensor

In [13]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [16]:
x_rand = torch.rand_like(x_data, dtype=torch.float32)
print(f"Random tensor: \n {x_data} \n")

Random tensor: 
 tensor([[1, 2],
        [3, 4]]) 



#### With random or constant values

In [18]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.8693, 0.6531, 0.7894],
        [0.1657, 0.9264, 0.7869]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



#### Tensor attributes

In [26]:
tensor = torch.rand(3,4)
print(tensor)

print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape (dimension) of tensor: {tensor.shape}")
print(f"Dimension of tensor: {tensor.ndim}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.3218, 0.0957, 0.9636, 0.8473],
        [0.8507, 0.2136, 0.2841, 0.6790],
        [0.5794, 0.9836, 0.9749, 0.6657]])
Datatype of tensor: torch.float32
Shape (dimension) of tensor: torch.Size([3, 4])
Dimension of tensor: 2
Device tensor is stored on: cpu


## Tensor operations

In [27]:
# move tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

#### Standard numpy-like indexing and slicing

In [28]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors
torch.cat to concatenate a sequence of tensors along a given dimension,

In [34]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Multiplying tensors

In [35]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# or
print(f"tensor * tensor \n {tensor * tensor} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



#### Matrix multiplication

In [36]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# or
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



#### In-place operations

In [37]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge to NumPy array

In [39]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
