In [1]:
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.5733, 0.7470, 0.0351],
        [0.6791, 0.2569, 0.4133],
        [0.8423, 0.5086, 0.1832],
        [0.0711, 0.3146, 0.7455],
        [0.9271, 0.9058, 0.5263]])


In [2]:
torch.cuda.is_available()

True

## PyTorch tensors

In [3]:
import numpy as np

#### Tensor from data

In [4]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

#### Tensor from np.array

In [6]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [7]:
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### Tensor from another tensor

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [9]:
x_rand = torch.rand_like(x_data, dtype=torch.float32)
print(f"Random tensor: \n {x_data} \n")

Random tensor: 
 tensor([[1, 2],
        [3, 4]]) 



#### With random or constant values

In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.8175, 0.2221, 0.7961],
        [0.3100, 0.9554, 0.8638]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



#### Tensor attributes

In [11]:
tensor = torch.rand(3,4)
print(tensor)

print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape (dimension) of tensor: {tensor.shape}")
print(f"Dimension of tensor: {tensor.ndim}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.1083, 0.5660, 0.9201, 0.7862],
        [0.6399, 0.6064, 0.3645, 0.1628],
        [0.0244, 0.3953, 0.5576, 0.7698]])
Datatype of tensor: torch.float32
Shape (dimension) of tensor: torch.Size([3, 4])
Dimension of tensor: 2
Device tensor is stored on: cpu


## Tensor operations

In [19]:
# move tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

#### Standard numpy-like indexing and slicing

In [13]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors
torch.cat to concatenate a sequence of tensors along a given dimension,

In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Multiplying tensors

In [15]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# or
print(f"tensor * tensor \n {tensor * tensor} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



#### Matrix multiplication

In [16]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# or
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



#### In-place operations

In [17]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge to NumPy array

In [18]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
